module.exports =  [
  {
    package: {
      name: 'react',
      scope: 'unscoped',
      version: '17.0.2',
      description:
        'React is a JavaScript library for building user interfaces.',
      keywords: ['react'],
      date: '2021-03-22T21:56:19.536Z',
      links: {
        npm: 'https://www.npmjs.com/package/react',
        homepage: 'https://reactjs.org/',
        repository: 'https://github.com/facebook/react',
        bugs: 'https://github.com/facebook/react/issues',
      },
      publisher: { username: 'gaearon', email: 'dan.abramov@gmail.com' },
      maintainers: [
        { username: 'sebmarkbage', email: 'sebastian@calyptus.eu' },
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'acdlite', email: 'npm@andrewclark.io' },
        { username: 'brianvaughn', email: 'briandavidvaughn@gmail.com' },
        { username: 'fb', email: 'opensource+npm@fb.com' },
        { username: 'trueadm', email: 'dg@domgan.com' },
        { username: 'sophiebits', email: 'npm@sophiebits.com' },
        { username: 'lunaruan', email: 'lunaris.ruan@gmail.com' },
      ],
    },
    score: {
      final: 0.9216894682875079,
      detail: {
        quality: 0.8629706748020751,
        popularity: 0.9189839750179767,
        maintenance: 0.9747253559731246,
      },
    },
    searchScore: 1010.41095,
    highlight: '<em>react</em>',
  },
  {
    package: {
      name: 'react-dom',
      scope: 'unscoped',
      version: '17.0.2',
      description: 'React package for working with the DOM.',
      keywords: ['react'],
      date: '2021-03-22T21:56:33.089Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-dom',
        homepage: 'https://reactjs.org/',
        repository: 'https://github.com/facebook/react',
        bugs: 'https://github.com/facebook/react/issues',
      },
      publisher: { username: 'gaearon', email: 'dan.abramov@gmail.com' },
      maintainers: [
        { username: 'sebmarkbage', email: 'sebastian@calyptus.eu' },
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'zpao', email: 'paul@oshannessy.com' },
        { username: 'acdlite', email: 'npm@andrewclark.io' },
        { username: 'brianvaughn', email: 'briandavidvaughn@gmail.com' },
        { username: 'fb', email: 'opensource+npm@fb.com' },
        { username: 'trueadm', email: 'dg@domgan.com' },
        { username: 'sophiebits', email: 'npm@sophiebits.com' },
        { username: 'lunaruan', email: 'lunaris.ruan@gmail.com' },
      ],
    },
    score: {
      final: 0.9179655678569316,
      detail: {
        quality: 0.8629706748020751,
        popularity: 0.9083323486056255,
        maintenance: 0.9747372668695435,
      },
    },
    searchScore: 9.852123,
    highlight: '<em>react</em>-dom',
  },
  {
    package: {
      name: 'react-is',
      scope: 'unscoped',
      version: '17.0.2',
      description: 'Brand checking of React Elements.',
      keywords: ['react'],
      date: '2021-03-22T21:56:47.976Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-is',
        homepage: 'https://reactjs.org/',
        repository: 'https://github.com/facebook/react',
        bugs: 'https://github.com/facebook/react/issues',
      },
      publisher: { username: 'gaearon', email: 'dan.abramov@gmail.com' },
      maintainers: [
        { username: 'sebmarkbage', email: 'sebastian@calyptus.eu' },
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'acdlite', email: 'npm@andrewclark.io' },
        { username: 'brianvaughn', email: 'briandavidvaughn@gmail.com' },
        { username: 'fb', email: 'opensource+npm@fb.com' },
        { username: 'trueadm', email: 'dg@domgan.com' },
        { username: 'sophiebits', email: 'npm@sophiebits.com' },
        { username: 'lunaruan', email: 'lunaris.ruan@gmail.com' },
      ],
    },
    score: {
      final: 0.8944065422282312,
      detail: {
        quality: 0.8629706748020751,
        popularity: 0.8410208468093388,
        maintenance: 0.9747372668695435,
      },
    },
    searchScore: 9.630924,
    highlight: '<em>react</em>-is',
  },
  {
    package: {
      name: 'react-redux',
      scope: 'unscoped',
      version: '7.2.6',
      description: 'Official React bindings for Redux',
      keywords: ['react', 'reactjs', 'redux'],
      date: '2021-10-25T17:05:23.326Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-redux',
        homepage: 'https://github.com/reduxjs/react-redux',
        repository: 'https://github.com/reduxjs/react-redux',
        bugs: 'https://github.com/reduxjs/react-redux/issues',
      },
      author: {
        name: 'Dan Abramov',
        email: 'dan.abramov@me.com',
        url: 'https://github.com/gaearon',
      },
      publisher: { username: 'timdorr', email: 'timdorr@timdorr.com' },
      maintainers: [
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'timdorr', email: 'timdorr@timdorr.com' },
        { username: 'acemarke', email: 'mark.erikson@gmail.com' },
      ],
    },
    score: {
      final: 0.8980670579317627,
      detail: {
        quality: 0.9417999945200225,
        popularity: 0.7588288060577313,
        maintenance: 0.9998199355872859,
      },
    },
    searchScore: 9.629831,
    highlight: '<em>react</em>-redux',
  },
  {
    package: {
      name: 'react-router',
      scope: 'unscoped',
      version: '6.0.2',
      description: 'Declarative routing for React',
      keywords: ['react', 'router', 'route', 'routing', 'history', 'link'],
      date: '2021-11-09T22:27:12.910Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-router',
        homepage: 'https://github.com/remix-run/react-router#readme',
        repository: 'https://github.com/remix-run/react-router',
        bugs: 'https://github.com/remix-run/react-router/issues',
      },
      author: { name: 'Remix Software', email: 'hello@remix.run' },
      publisher: { username: 'mjackson', email: 'npm@mjackson.me' },
      maintainers: [
        { username: 'timdorr', email: 'timdorr@timdorr.com' },
        { username: 'mjackson', email: 'npm@mjackson.me' },
        { username: 'chancestrickland', email: 'hi@chance.dev' },
      ],
    },
    score: {
      final: 0.8528066680761939,
      detail: {
        quality: 0.7681005543109671,
        popularity: 0.7782274586224937,
        maintenance: 0.9999911179000887,
      },
    },
    searchScore: 9.119574,
    highlight: '<em>react</em>-router',
  },
  {
    package: {
      name: 'react-refresh',
      scope: 'unscoped',
      version: '0.11.0',
      description:
        'React is a JavaScript library for building user interfaces.',
      keywords: ['react'],
      date: '2021-11-09T20:24:14.251Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-refresh',
        homepage: 'https://reactjs.org/',
        repository: 'https://github.com/facebook/react',
        bugs: 'https://github.com/facebook/react/issues',
      },
      publisher: { username: 'gaearon', email: 'dan.abramov@gmail.com' },
      maintainers: [
        { username: 'sebmarkbage', email: 'sebastian@calyptus.eu' },
        { username: 'necolas', email: 'nicolasgallagher@gmail.com' },
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'threepointone', email: 'threepointone@gmail.com' },
        { username: 'acdlite', email: 'npm@andrewclark.io' },
        { username: 'brianvaughn', email: 'briandavidvaughn@gmail.com' },
        { username: 'trueadm', email: 'dg@domgan.com' },
        { username: 'lunaruan', email: 'lunaris.ruan@gmail.com' },
      ],
    },
    flags: { unstable: true },
    score: {
      final: 0.8538856387715783,
      detail: {
        quality: 0.8372543571171036,
        popularity: 0.7472893949488775,
        maintenance: 0.9747372668695435,
      },
    },
    searchScore: 9.10759,
    highlight: '<em>react</em>-refresh',
  },
  {
    package: {
      name: 'react-i18next',
      scope: 'unscoped',
      version: '11.13.0',
      description:
        'Internationalization for react done right. Using the i18next i18n ecosystem.',
      keywords: [
        'i18next',
        'internationalization',
        'i18n',
        'translation',
        'localization',
        'l10n',
        'globalization',
        'react',
        'reactjs',
      ],
      date: '2021-10-28T17:49:22.575Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-i18next',
        homepage: 'https://github.com/i18next/react-i18next',
        repository: 'https://github.com/i18next/react-i18next',
        bugs: 'https://github.com/i18next/react-i18next/issues',
      },
      author: {
        name: 'Jan MÃ¼hlemann',
        email: 'jan.muehlemann@gmail.com',
        url: 'https://github.com/jamuhl',
        username: 'jamuhl',
      },
      publisher: { username: 'adrai', email: 'adriano@raiano.ch' },
      maintainers: [
        { username: 'adrai', email: 'adriano@raiano.ch' },
        { username: 'jamuhl', email: 'jan.muehlemann@gmail.com' },
      ],
    },
    score: {
      final: 0.8468818962299767,
      detail: {
        quality: 0.9987582678534606,
        popularity: 0.5635840613527797,
        maintenance: 0.9999999840013303,
      },
    },
    searchScore: 8.904696,
    highlight: '<em>react</em>-i18next',
  },
  {
    package: {
      name: 'react-dropzone',
      scope: 'unscoped',
      version: '11.4.2',
      description: 'Simple HTML5 drag-drop zone with React.js',
      keywords: ['react-component', 'react', 'drag', 'drop', 'upload'],
      date: '2021-09-23T23:58:09.980Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-dropzone',
        homepage: 'https://github.com/react-dropzone/react-dropzone',
        repository: 'https://github.com/react-dropzone/react-dropzone',
        bugs: 'https://github.com/react-dropzone/react-dropzone/issues',
      },
      author: { name: 'Param Aggarwal' },
      publisher: { username: 'rolandjitsu', email: 'rolandjitsu@gmail.com' },
      maintainers: [
        { username: 'rolandjitsu', email: 'rolandjitsu@gmail.com' },
        { username: 'rxmarbles', email: 'rmarkins@gmail.com' },
        { username: 'okonet', email: 'andrey@okonet.ru' },
      ],
    },
    score: {
      final: 0.8411086539345276,
      detail: {
        quality: 0.9527343756267316,
        popularity: 0.5888217135899354,
        maintenance: 0.9977164042572307,
      },
    },
    searchScore: 8.903593,
    highlight: '<em>react</em>-dropzone',
  },
  {
    package: {
      name: 'react-popper',
      scope: 'unscoped',
      version: '2.2.5',
      description: 'Official library to use Popper on React projects',
      keywords: [
        'react',
        'react-popper',
        'popperjs',
        'component',
        'drop',
        'tooltip',
        'popover',
      ],
      date: '2021-03-25T12:09:54.990Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-popper',
        homepage: 'https://popper.js.org/react-popper',
        repository: 'https://github.com/popperjs/react-popper',
        bugs: 'https://github.com/popperjs/react-popper/issues',
      },
      author: {
        name: 'Travis Arnold',
        email: 'travis@souporserious.com',
        url: 'http://souporserious.com',
      },
      publisher: { username: 'fezvrasta', email: 'federico.zivolo@gmail.com' },
      maintainers: [
        { username: 'fezvrasta', email: 'federico.zivolo@gmail.com' },
        { username: 'souporserious', email: 'ftntravis@gmail.com' },
      ],
    },
    score: {
      final: 0.8363222819295741,
      detail: {
        quality: 0.9463920650543609,
        popularity: 0.5916380338471459,
        maintenance: 0.9866610016193282,
      },
    },
    searchScore: 8.897702,
    highlight: '<em>react</em>-popper',
  },
  {
    package: {
      name: 'react-query',
      scope: 'unscoped',
      version: '3.32.1',
      description:
        'Hooks for managing, caching and syncing asynchronous and remote data in React',
      date: '2021-11-06T21:47:42.202Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-query',
        homepage: 'https://github.com/tannerlinsley/react-query#readme',
        repository: 'https://github.com/tannerlinsley/react-query',
        bugs: 'https://github.com/tannerlinsley/react-query/issues',
      },
      author: { name: 'tannerlinsley' },
      publisher: {
        username: 'tannerlinsley',
        email: 'tannerlinsley@gmail.com',
      },
      maintainers: [
        { username: 'tannerlinsley', email: 'tannerlinsley@gmail.com' },
      ],
    },
    score: {
      final: 0.8336618405530448,
      detail: {
        quality: 0.9662352754522596,
        popularity: 0.5536893083353343,
        maintenance: 1,
      },
    },
    searchScore: 8.893776,
    highlight: '<em>react</em>-query',
  },
  {
    package: {
      name: 'react-table',
      scope: 'unscoped',
      version: '7.7.0',
      description:
        'Hooks for building lightweight, fast and extendable datagrids for React',
      keywords: ['react', 'table', 'react-table', 'datagrid'],
      date: '2021-04-25T22:58:20.146Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-table',
        homepage: 'https://react-table.tanstack.com',
        repository: 'https://github.com/tannerlinsley/react-table',
        bugs: 'https://github.com/tannerlinsley/react-table/issues',
      },
      publisher: {
        username: 'tannerlinsley',
        email: 'tannerlinsley@gmail.com',
      },
      maintainers: [
        { username: 'tannerlinsley', email: 'tannerlinsley@gmail.com' },
      ],
    },
    score: {
      final: 0.8317770820844628,
      detail: {
        quality: 0.9798002887619728,
        popularity: 0.5371364633128667,
        maintenance: 0.9995406665610505,
      },
    },
    searchScore: 8.873669,
    highlight: '<em>react</em>-table',
  },
  {
    package: {
      name: 'react-router-dom',
      scope: 'unscoped',
      version: '6.0.2',
      description: 'Declarative routing for React web applications',
      keywords: ['react', 'router', 'route', 'routing', 'history', 'link'],
      date: '2021-11-09T22:27:14.915Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-router-dom',
        homepage: 'https://github.com/remix-run/react-router#readme',
        repository: 'https://github.com/remix-run/react-router',
        bugs: 'https://github.com/remix-run/react-router/issues',
      },
      author: { name: 'Remix Software', email: 'hello@remix.run' },
      publisher: { username: 'mjackson', email: 'npm@mjackson.me' },
      maintainers: [
        { username: 'timdorr', email: 'timdorr@timdorr.com' },
        { username: 'mjackson', email: 'npm@mjackson.me' },
        { username: 'chancestrickland', email: 'hi@chance.dev' },
      ],
    },
    score: {
      final: 0.8590330692309731,
      detail: {
        quality: 0.7611962071689224,
        popularity: 0.8019351880436153,
        maintenance: 0.9999911179000887,
      },
    },
    searchScore: 8.833718,
    highlight: '<em>react</em>-router-dom',
  },
  {
    package: {
      name: 'react-hook-form',
      scope: 'unscoped',
      version: '7.19.3',
      description:
        'Performant, flexible and extensible forms library for React Hooks',
      keywords: [
        'react',
        'hooks',
        'form',
        'forms',
        'form-validation',
        'validation',
        'typescript',
        'react-hooks',
      ],
      date: '2021-11-10T06:38:44.550Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-hook-form',
        homepage: 'https://www.react-hook-form.com',
        repository: 'https://github.com/react-hook-form/react-hook-form',
        bugs: 'https://github.com/react-hook-form/react-hook-form/issues',
      },
      author: { email: 'bluebill1049@hotmail.com' },
      publisher: { username: 'bluebill1049', email: 'bluebill1049@gmail.com' },
      maintainers: [
        { username: 'bluebill1049', email: 'bluebill1049@gmail.com' },
      ],
    },
    score: {
      final: 0.8595325775329689,
      detail: {
        quality: 0.9973065813667863,
        popularity: 0.6009731517798086,
        maintenance: 1,
      },
    },
    searchScore: 8.816739,
    highlight: '<em>react</em>-hook-form',
  },
  {
    package: {
      name: 'react-bootstrap',
      scope: 'unscoped',
      version: '2.0.1',
      description: 'Bootstrap 5 components built with React',
      keywords: ['react', 'ecosystem-react', 'react-component', 'bootstrap'],
      date: '2021-10-29T05:35:45.964Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-bootstrap',
        homepage: 'https://react-bootstrap.github.io/',
        repository: 'https://github.com/react-bootstrap/react-bootstrap',
        bugs: 'https://github.com/react-bootstrap/react-bootstrap/issues',
      },
      author: { name: 'Stephen J. Collings', email: 'stevoland@gmail.com' },
      publisher: { username: 'kytsang', email: 'ktsang.work@gmail.com' },
      maintainers: [
        { username: 'monastic.panic', email: 'monastic.panic@gmail.com' },
        { username: 'taion', email: 'tesrin@gmail.com' },
        { username: 'kytsang', email: 'ktsang.work@gmail.com' },
      ],
    },
    score: {
      final: 0.831283981860773,
      detail: {
        quality: 0.8914485882136148,
        popularity: 0.611860108040852,
        maintenance: 0.999138193092544,
      },
    },
    searchScore: 8.779171,
    highlight: '<em>react</em>-bootstrap',
  },
  {
    package: {
      name: 'react-markdown',
      scope: 'unscoped',
      version: '7.1.0',
      description: 'Render Markdown as React components',
      keywords: [
        'remark',
        'unified',
        'markdown',
        'commonmark',
        'gfm',
        'ast',
        'react',
        'react-component',
        'component',
      ],
      date: '2021-10-21T14:01:40.360Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-markdown',
        homepage: 'https://github.com/remarkjs/react-markdown#readme',
        repository: 'https://github.com/remarkjs/react-markdown',
        bugs: 'https://github.com/remarkjs/react-markdown/issues',
      },
      author: { name: 'Espen Hovlandsdal', email: 'espen@hovlandsdal.com' },
      publisher: { username: 'wooorm', email: 'tituswormer@gmail.com' },
      maintainers: [
        { username: 'johno', email: 'johnotander@gmail.com' },
        { username: 'wooorm', email: 'tituswormer@gmail.com' },
      ],
    },
    score: {
      final: 0.8273406592113479,
      detail: {
        quality: 0.9614707177373903,
        popularity: 0.5397580335437697,
        maintenance: 0.9999546632851757,
      },
    },
    searchScore: 8.757852,
    highlight: '<em>react</em>-markdown',
  },
  {
    package: {
      name: 'react-intl',
      scope: 'unscoped',
      version: '5.21.1',
      description:
        'Internationalize React apps. This library provides React components and an API to format dates, numbers, and strings, including pluralization and handling translations.',
      keywords: [
        'intl',
        'i18n',
        'internationalization',
        'locale',
        'localization',
        'globalization',
        'react',
        'reactjs',
        'format',
        'formatting',
        'translate',
        'translation',
      ],
      date: '2021-11-09T17:17:17.753Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-intl',
        homepage: 'https://formatjs.io/docs/react-intl',
        repository: 'https://github.com/formatjs/formatjs',
        bugs: 'https://github.com/formatjs/formatjs/issues',
      },
      author: { name: 'Eric Ferraiuolo', email: 'edf@ericf.me' },
      publisher: { username: 'longlho', email: 'holevietlong@gmail.com' },
      maintainers: [
        { username: 'longlho', email: 'holevietlong@gmail.com' },
        { username: 'redonkulus', email: 'seth@bertalotto.net' },
        { username: 'pyrocat', email: 'dinglinjie+npm@gmail.com' },
        { username: 'caridy', email: 'caridy@gmail.com' },
        { username: 'juandopazo', email: 'juan@dopazo.me' },
        { username: 'clarle', email: 'contact@clarle.com' },
        { username: 'okuryu', email: 'okuryu@okuryu.com' },
        { username: 'ericf', email: 'eferraiuolo@gmail.com' },
      ],
    },
    score: {
      final: 0.8157613029031862,
      detail: {
        quality: 0.9027793038310707,
        popularity: 0.5626830392548728,
        maintenance: 0.9942527086133128,
      },
    },
    searchScore: 8.728176,
    highlight: '<em>react</em>-intl',
  },
  {
    package: {
      name: 'react-toastify',
      scope: 'unscoped',
      version: '8.0.3',
      description: 'React notification made easy',
      keywords: [
        'react',
        'notification',
        'toast',
        'react-component',
        'react-toastify',
        'push',
        'alert',
      ],
      date: '2021-09-24T20:59:00.783Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-toastify',
        homepage: 'https://github.com/fkhadra/react-toastify#readme',
        repository: 'https://github.com/fkhadra/react-toastify',
        bugs: 'https://github.com/fkhadra/react-toastify/issues',
      },
      author: {
        name: 'Fadi Khadra',
        email: 'fdkhadra@gmail.com',
        url: 'https://fkhadra.github.io',
        username: 'sniphpet',
      },
      publisher: { username: 'sniphpet', email: 'fdkhadra@gmail.com' },
      maintainers: [{ username: 'sniphpet', email: 'fdkhadra@gmail.com' }],
    },
    score: {
      final: 0.8245297414263275,
      detail: {
        quality: 0.9876393344414787,
        popularity: 0.5119665280790855,
        maintenance: 0.9972847321891547,
      },
    },
    searchScore: 8.728096,
    highlight: '<em>react</em>-toastify',
  },
  {
    package: {
      name: 'react-use',
      scope: 'unscoped',
      version: '17.3.1',
      description: 'Collection of React Hooks',
      date: '2021-08-31T22:31:44.123Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-use',
        homepage: 'https://github.com/streamich/react-use#readme',
        repository: 'https://github.com/streamich/react-use',
        bugs: 'https://github.com/streamich/react-use/issues',
      },
      author: { name: '@streamich' },
      publisher: { username: 'streamich', email: 'vadimsdaleckis@gmail.com' },
      maintainers: [
        { username: 'streamich', email: 'vadimsdaleckis@gmail.com' },
      ],
    },
    score: {
      final: 0.8088046962147493,
      detail: {
        quality: 0.943614488330602,
        popularity: 0.5533514926795929,
        maintenance: 0.9487066493648892,
      },
    },
    searchScore: 8.680548,
    highlight: '<em>react</em>-use',
  },
  {
    package: {
      name: 'react-test-renderer',
      scope: 'unscoped',
      version: '17.0.2',
      description: 'React package for snapshot testing.',
      keywords: ['react', 'react-native', 'react-testing'],
      date: '2021-03-22T21:57:03.893Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-test-renderer',
        homepage: 'https://reactjs.org/',
        repository: 'https://github.com/facebook/react',
        bugs: 'https://github.com/facebook/react/issues',
      },
      publisher: { username: 'gaearon', email: 'dan.abramov@gmail.com' },
      maintainers: [
        { username: 'sebmarkbage', email: 'sebastian@calyptus.eu' },
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'zpao', email: 'paul@oshannessy.com' },
        { username: 'acdlite', email: 'npm@andrewclark.io' },
        { username: 'brianvaughn', email: 'briandavidvaughn@gmail.com' },
        { username: 'fb', email: 'opensource+npm@fb.com' },
        { username: 'trueadm', email: 'dg@domgan.com' },
        { username: 'sophiebits', email: 'npm@sophiebits.com' },
        { username: 'lunaruan', email: 'lunaris.ruan@gmail.com' },
      ],
    },
    score: {
      final: 0.8464569179080064,
      detail: {
        quality: 0.8629706748020751,
        popularity: 0.7040219201801248,
        maintenance: 0.9747372668695435,
      },
    },
    searchScore: 8.648325,
    highlight: '<em>react</em>-test-renderer',
  },
  {
    package: {
      name: 'react-colorful',
      scope: 'unscoped',
      version: '5.5.0',
      description:
        'ðŸŽ¨ A tiny (2,5 KB) color picker component for React and Preact apps. Fast, well-tested, dependency-free, mobile-friendly and accessible',
      keywords: [
        'react',
        'color picker',
        'react-component',
        'colorpicker',
        'tiny',
        'hex',
        'color',
        'front-end',
        'color-picker',
        'accessible',
        'react-color',
        'accessibility',
        'aria',
        'a11y',
        'wai-aria',
      ],
      date: '2021-09-28T16:19:51.698Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-colorful',
        homepage: 'https://omgovich.github.io/react-colorful',
      },
      author: {
        name: 'Vlad Shilov',
        email: 'omgovich@ya.ru',
        username: 'omgovich',
      },
      publisher: { username: 'omgovich', email: 'omgovich@ya.ru' },
      maintainers: [{ username: 'omgovich', email: 'omgovich@ya.ru' }],
    },
    score: {
      final: 0.8096798050213561,
      detail: {
        quality: 0.9998310219158806,
        popularity: 0.45638487000109107,
        maintenance: 0.9999879827034572,
      },
    },
    searchScore: 8.570902,
    highlight: '<em>react</em>-colorful',
  },
  {
    package: {
      name: 'react-fast-compare',
      scope: 'unscoped',
      version: '3.2.0',
      description:
        'Fastest deep equal comparison for React. Great for React.memo & shouldComponentUpdate. Also really fast general-purpose deep comparison.',
      keywords: [
        'fast',
        'equal',
        'react',
        'compare',
        'shouldComponentUpdate',
        'deep-equal',
      ],
      date: '2020-05-28T15:49:05.777Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-fast-compare',
        homepage: 'https://github.com/FormidableLabs/react-fast-compare',
        repository: 'https://github.com/FormidableLabs/react-fast-compare',
        bugs: 'https://github.com/FormidableLabs/react-fast-compare/issues',
      },
      author: { name: 'Chris Bolin' },
      publisher: { username: 'kale-stew', email: 'kylieastewart@gmail.com' },
      maintainers: [
        { username: 'beccanelson', email: 'beccanelsonbailey@gmail.com' },
        { username: 'michaelmerrill', email: 'michael@michaelmerrill.me' },
        { username: 'sarmeyer', email: 'sarahmichellemeyer@gmail.com' },
        {
          username: 'mariano-formidable',
          email: 'mariano.martinez@formidable.com',
        },
        { username: 'carlospaelinck', email: 'me@carlos.dev' },
        { username: 'ryanisinallofus', email: 'ryanrray@gmail.com' },
        { username: 'samwhale', email: 'samuelestrella226@gmail.com' },
        { username: 'bmathews', email: 'spoonart@gmail.com' },
        { username: 'ryan.roemer', email: 'ryan@loose-bits.com' },
        { username: 'paulathevalley', email: 'lavalle.paula@gmail.com' },
        { username: 'tptee', email: 'tyler@tylerpaulthompson.com' },
        { username: 'formidable-owner', email: 'admin@formidablelabs.com' },
        { username: 'ebrillhart', email: 'emma.brillhart@gmail.com' },
        { username: 'stefvhuynh', email: 'huynh.stefan@gmail.com' },
        { username: 'eastridge', email: 'ryan@eastridge.me' },
        { username: 'exogen', email: 'exogen@gmail.com' },
        { username: 'boygirl', email: 'lauren.eastridge@formidable.com' },
        { username: 'philpl', email: 'phil@kitten.sh' },
        { username: 'hartzis', email: 'brianhartz@gmail.com' },
        { username: 'mfulgham', email: 'monet.fulgham@formidable.com' },
        { username: 'jmcbee1', email: 'jmcbee1@gmail.com' },
        { username: 'formidablelabs', email: 'npm@formidablelabs.com' },
        { username: 'carbonrobot', email: 'carbonrobot@gmail.com' },
        { username: 'manosim', email: 'hello@manos.im' },
        { username: 'masiddee', email: 'mansoor@msiddeeq.com' },
        { username: 'gksander', email: 'gksander93@gmail.com' },
        { username: 'chrisbolin', email: 'bolin.chris@gmail.com' },
      ],
    },
    score: {
      final: 0.8386536496825925,
      detail: {
        quality: 0.9950021862511585,
        popularity: 0.5433878847131848,
        maintenance: 0.9999063833075152,
      },
    },
    searchScore: 8.543969,
    highlight: '<em>react</em>-fast-compare',
  },
  {
    package: {
      name: 'react-player',
      scope: 'unscoped',
      version: '2.9.0',
      description:
        'A React component for playing a variety of URLs, including file paths, YouTube, Facebook, Twitch, SoundCloud, Streamable, Vimeo, Wistia and DailyMotion',
      keywords: [
        'react',
        'media',
        'player',
        'video',
        'audio',
        'youtube',
        'facebook',
        'twitch',
        'soundcloud',
        'streamable',
        'vimeo',
        'wistia',
        'dailymotion',
        'hls',
        'dash',
        'react-component',
      ],
      date: '2021-02-17T23:57:56.593Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-player',
        homepage: 'https://github.com/CookPete/react-player',
        repository: 'https://github.com/CookPete/react-player',
        bugs: 'https://github.com/CookPete/react-player/issues',
      },
      author: {
        name: 'Pete Cook',
        email: 'pete@cookpete.com',
        url: 'http://github.com/cookpete',
        username: 'cookpete',
      },
      publisher: { username: 'cookpete', email: 'pete@cookpete.com' },
      maintainers: [{ username: 'cookpete', email: 'pete@cookpete.com' }],
    },
    score: {
      final: 0.7948206304715623,
      detail: {
        quality: 0.9616753957858223,
        popularity: 0.4515627081230232,
        maintenance: 0.9950601825507357,
      },
    },
    searchScore: 8.456163,
    highlight: '<em>react</em>-player',
  },
  {
    package: {
      name: 'react-scripts',
      scope: 'unscoped',
      version: '4.0.3',
      description: 'Configuration and scripts for Create React App.',
      date: '2021-02-22T18:22:29.697Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-scripts',
        homepage: 'https://github.com/facebook/create-react-app#readme',
        repository: 'https://github.com/facebook/create-react-app',
        bugs: 'https://github.com/facebook/create-react-app/issues',
      },
      publisher: { username: 'iansu', email: 'ian@iansutherland.ca' },
      maintainers: [
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'fb', email: 'opensource+npm@fb.com' },
        { username: 'timer', email: 'timer150@gmail.com' },
        { username: 'iansu', email: 'ian@iansutherland.ca' },
        { username: 'ianschmitz', email: 'ianschmitz@gmail.com' },
      ],
    },
    score: {
      final: 0.7944485565812917,
      detail: {
        quality: 0.6758427017718718,
        popularity: 0.7704017036493116,
        maintenance: 0.9201575707784888,
      },
    },
    searchScore: 8.430321,
    highlight: '<em>react</em>-scripts',
  },
  {
    package: {
      name: 'react-dev-utils',
      scope: 'unscoped',
      version: '11.0.4',
      description: 'webpack utilities used by Create React App',
      date: '2021-03-08T19:28:26.653Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-dev-utils',
        homepage: 'https://github.com/facebook/create-react-app#readme',
        repository: 'https://github.com/facebook/create-react-app',
        bugs: 'https://github.com/facebook/create-react-app/issues',
      },
      publisher: { username: 'gaearon', email: 'dan.abramov@gmail.com' },
      maintainers: [
        { username: 'gaearon', email: 'dan.abramov@gmail.com' },
        { username: 'fb', email: 'opensource+npm@fb.com' },
        { username: 'timer', email: 'timer150@gmail.com' },
        { username: 'iansu', email: 'ian@iansutherland.ca' },
        { username: 'ianschmitz', email: 'ianschmitz@gmail.com' },
      ],
    },
    score: {
      final: 0.8200780025068618,
      detail: {
        quality: 0.7340389265137977,
        popularity: 0.7937462136578615,
        maintenance: 0.9201575707784888,
      },
    },
    searchScore: 8.412029,
    highlight: '<em>react</em>-dev-utils',
  },
  {
    package: {
      name: 'react-responsive',
      scope: 'unscoped',
      version: '9.0.0-beta.4',
      description: 'Media queries in react for responsive design',
      keywords: [
        'css',
        'react-component',
        'viewport',
        'react',
        'mobile',
        'media queries',
        'respond',
        'media query',
        'matchMedia',
        'responsive',
        'component',
      ],
      date: '2021-09-03T19:37:15.575Z',
      links: {
        npm: 'https://www.npmjs.com/package/react-responsive',
        homepage: 'http://github.com/contra/react-responsive',
        repository: 'https://github.com/contra/react-responsive',
        bugs: 'https://github.com/contra/react-responsive/issues',
      },
      author: {
        name: 'Contra',
        email: 'yo@contra.io',
        url: 'https://contra.io',
      },
      publisher: { username: 'contra', email: 'yo@contra.io' },
      maintainers: [
        { username: 'fractal', email: 'contact@wearefractal.com' },
        { username: 'yocontra', email: 'ericbombhax@gmail.com' },
      ],
    },
    score: {
      final: 0.7923154859354391,
      detail: {
        quality: 0.9417999945200225,
        popularity: 0.4565950097765774,
        maintenance: 0.9999063833075152,
      },
    },
    searchScore: 8.392391,
    highlight: '<em>react</em>-responsive',
  },
];
